name: Deploy Back-end

on:
  push:
    branches:
      - 'dev'
      - 'master'
    paths:
      - 'sc-platform-api/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push app Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./sc-platform-api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ficesolutions/sc-platform-api:${{ github.ref_name }}
